name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_TARGET: ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build Binary
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: true
        run: |
          go build -ldflags="-s -w" -o Polybub ./

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Stop the App
        run: |
          ssh $SSH_TARGET "sudo systemctl stop Polybub || true"
          ssh $SSH_TARGET "sudo systemctl reset-failed Polybub || true"

      - name: Copy Secrets to server
        run: |
          cat > config.json <<'EOF'
          ${{ secrets.CONFIG }}
          EOF
          scp config.json $SSH_TARGET:/var/www/app/Polybub/config.json

      - name: Copy Binary to Remote
        run: |
          scp Polybub $SSH_TARGET:/var/www/app/Polybub/Polybub

      - name: Start App
        run: |
          ssh $SSH_TARGET "sudo systemctl daemon-reload"
          ssh $SSH_TARGET "sudo /usr/bin/systemd-run --unit=Polybub --property=User=github_agent --property=ReadWritePaths=/var/www/app/Polybub/.db /var/www/app/Polybub/Polybub"

      - name: Clean up
        run: |
          ssh $SSH_TARGET "rm -rf /var/www/app/Polybub/config.json"
          rm -rf config.json
          rm -rf ~/.ssh
